const clues = [
	'Mark Twain prop',
	'Confute',
	'Hardly a he-man',
	'Skeptical grunt',
	'Conscious',
	'Turn red from embarrassment',
	'Kind of point',
	'Get around',
	'Like some forces',
	"Do one's duty",
	'Scrubland',
	'Tower over',
	'Fashion figure',
	'Fate',
	'Perform lousily',
	'School division',
	'Hospital caution',
	'CATCHER',
	'Diminish in intensity',
	'Fake',
	'*"Catch-22" character',
	'Ruination',
	'Unwilted',
	'Pizza feature',
	'Bird decoy',
	'Theme of this puzzle',
	'Lower in public estimation',
	'Tie the knot',
	"Don't just stand there",
	'Eccentric',
	'One of 7-Down',
	"It's often waxed",
	'DNA structure',
	"Raven's call",
	'Office folk',
	'First-anniversary gift',
	'Hungry',
	'Have puppies',
	"It's a drag to fishermen",
	'Top',
	'Desert home',
	'Nutso',
	'Farmer in the spring',
	'Indemnify',
	'1 or 2',
	'Jalopy',
	'... a hen',
	'Net feat',
	'Copycat',
	'Feared destination in "Lady and the Tramp"',
	'Writer Gorky',
	'Cool fabric',
	'Like some goals, sadly',
	'Bygone Crayola shade',
	'Dunce',
	'Out into view',
	'Blue-ribbon position',
	'Determined policy',
	"Mideastern dancer's asset",
	'Banned article of trade',
	'Squalid',
	'Computer command',
	'Long (for)',
	'Bathtub part',
	'Hush money',
	'Full-bodied ale',
	'Control ___',
	'Unmannered',
	'Water ride',
	'Refuse',
	'Go along (with)',
	"Trial's partner",
	'Multiflavor ice cream',
	'Speak in court',
	'Extort from',
	'___ team (assault unit)',
	'Wrist action',
	'Item on a pole',
	'Tempter',
	'Attack locale',
	'Hydrangea, e.g.',
	'Turn aside',
	'Complex ecologic community',
	'Flap in the fashion industry',
	'Kick off',
	'Hail',
	'Dead duck',
	'Automaton',
	'Full of vigor',
	"Off one's trolley",
	'Spherical',
	'Thorough check',
	'Fibbing',
	'Symbol of magnetic field strength',
	'Childbirth',
	'Cay',
	'Kind of duty',
	"Smithy's furnace",
	'Hokey',
	'Drop down, in London?',
	'Kind of training',
	'Greek ___',
	'Fine-print type',
	'Hot',
	'Floral arrangement',
	'Attempt',
	'Greenland sight',
	'Go through',
	"Food that's stuck on a plate",
	'Early trade union',
	'Unawares',
	'Kind of skill or home',
	'Byrd book',
	'Break out, in a way',
	'Overexcited',
	'Handy digit',
	"Bride's worldly possessions",
	'Should, with "to"',
	'"Twelfth Night" character',
	'Kind of treat',
	'Series sample',
	"Preppy's fabric",
	'Hale-Bopp, e.g.',
	'Short trip',
	'Cleansing regimen, for some',
	'Silver, e.g.',
	'Bottomless pit',
	'Sound of an empty stomach',
	'Chuck',
	'Carton complement',
	'Smashed',
	'Shorelines do it',
	'Series opener?',
	'Overcharge',
	'Select on a computer',
	'Tobacco pipe',
	'First-rate',
	'Place for an exchange',
	'Rather soft',
	'Say suddenly',
	'Take it easy',
	'Brittany or Aquitaine, once',
	'Strain locus',
	'Repairman',
	'Get together',
	'Scamp',
	'In the worst way',
	'Kind of cookie',
	'Concise',
	'Flashy',
	'"Relax, bro!"',
	'Shore bird',
	'Part of a screwdriver',
	'Better penalty meter? (5)',
	'Not so risky',
	"Marconi's invention",
	'Cheek cosmetic',
	'Toehold?',
	'React violently, in a way',
	'Penned',
	'What a mouse ran up, in a rhyme',
	'Part of Espana',
	'Warehouse',
	'Put to the test',
	'Fetch',
	'Crack',
	'Chiseler',
	'Detergent target',
	'Be jubilant',
	'Theater employee',
	'Significant time',
	'Any Tom, Dick and Harry',
	'Huddle ender',
	'Horned zoo beast',
	'Like the flu',
	'Like some traffic barriers',
	'Billiard stroke',
	'Kind of boom',
	'Like some statistics',
	'Follow',
	'Taking advantage of',
	'Miss in the comics',
	"Boxer's nickname",
	'It can help keep time',
	'Slow down',
	'Play pizzicato',
	'Mania',
	'Kick',
	'Jaded',
	'Hard to please',
	'Intense',
	'Boat to Staten Island',
	'Song much played on the radio',
	'Tropical animal',
	'Folklore dwarf',
	'Fuse',
	'"Concentration" puzzle',
	'Leg up',
	'Supporting beam',
	'Long bout',
	'Go-getter',
	'Highly hackneyed',
	"Batter's woe",
	'Monomaniac, informally',
	'Stuff to the gills',
	'Express doubt about',
	'What each of the four long answers in this puzzle is',
	'Party handout',
	'Westminster, for one',
	'Zestful',
	'Article I put in "Politically Correct" produces widespread alarm (5)',
	'Environment-friendly energy choice',
	"Queen's county",
	"Stockholder's prerogative",
	"West __ (site of Arnold's attempted betrayal)",
	'Gog, of film sci-fi',
	'Puncture',
	'React to a bad joke, perhaps',
	'Hamper',
	'Small hill',
	'Babydoll',
	'Hit plenty hard',
	'Organize, as an exhibit',
	'Brisk',
	'Had the know-how',
	'Squeezed water out of',
	'Beacon',
	'"___ Calloways" (1965 Disney film)',
	'Having tears',
	'Shattered pane piece',
	'Fold',
	'Up in the sky',
	'Expertise',
	'Church V.I.P.',
	'Formulate',
	'Indulge',
	'VCR button',
	"Worrier's woe, it's said",
	'Kin of hyper-',
	"Repeated Chris O'Donnell movie role",
	'Motive questioner',
	'Welcome smell',
	'Make watertight',
	'Deal binder',
	'City for Miss Kitty',
	'Hogwash',
	'Unspoken',
	'Additional',
	'Considerable irritant',
	'Treasure store',
	'Chap',
	'Lively, as an imagination',
	'Let slip',
	'Sound from the bleachers',
	'Strangle',
	'Indian coin',
	'Yucky',
	'Keen',
	'Forward',
	'Pickle juice',
	'Linen or denim',
	'Keep for oneself',
	'Sugary',
	'Calendar page',
	'Come to an end',
	'Band instrument?',
	'Now',
	'Zero in (on)',
	'Got wind of, old-style',
	'Razz',
	'Provide for, as a party',
	'Flick',
	'Prepare, as mushrooms',
	'Grant',
	'Ask for more Time?',
	'Not our',
	'Not be careful with a bucket',
	'Remove, Soviet-style',
	'Treasure site',
	'Stop',
	'Adhesive resin',
	'Pretty maiden of Greek myth',
	'*With 44-Down, not turning up as expected in a search',
	'Strong will?',
	'Potbelly, e.g.',
	'Humble',
	'Quite a nose',
	'Metaphor or irony, e.g.',
	'Not as many',
	'Protection against chills',
	'Kind of chart',
	'Cause for pause',
	'Quick raid',
	'Daunt',
	'Flight of steps',
	'With 42-Across, a famous pirate',
	'Bomb ___',
	'Flush variety',
	'Big piece',
	'Prepare garlic, perhaps',
	'Word of reproach',
	'Place for a peck',
	'Capacious',
	'Eclat',
	'Degas\'s "Le ___ de la danse"',
	'Freight',
	'Zinc ___',
	'Not legitimate evidence',
	"Popeye's sweetie",
	'Motionless',
	'Crooked',
	'Bank job',
	'Exhibited',
	'Like barbecue sauce',
	'Rash',
	'Refuse',
	"Gal's guy",
	'Stage between egg and pupa',
	'Do without',
	'Tale',
	'Dangerous, colloquially',
	'Teach, as dog tricks, for example',
	'Noted marine watercolorist',
	"Sheriff's star, e.g.",
	'Central point',
	'Shrewd',
	'Womb contents',
	"Sundance Kid's partner, ___ Cassidy",
	"You can't take it seriously",
	'Cast',
	'A bit blotto',
	'One may be precious',
	'Submit',
	'Probe (into)',
	'Existence',
	'Scrub',
	'Major Czech export',
	'Dungeons & Dragons sort',
	'Leftover piece',
	'It may be advanced',
	'Pivotal point',
	"Collector's book",
	'___ for (substantiate)',
	'Money in the bank',
	'Coronet',
	'Inched',
	'Lazy waters',
	'A-test site, perhaps',
	'Mount Vernon, for one',
	'Sound of old floorboards',
	'Theatrical',
	'Stage',
	'Foam',
	'The third "D" of 3-D',
	'Despondency',
	'Result of a bank failure?',
	'Characteristic',
	'Size',
	'Godliness',
	'Check writer',
	'Stir up, in a way',
	'Hydroplane part',
	'Transplant need',
	'Make up',
	'Top-notch',
	'Kitchen garment',
	'Gusted',
	'Important West Indies crop',
	'Vanquished',
	'Ideas, opinions, etc.',
	'Exhibit annoying satisfaction',
	'Worse than bad',
	'Critical point',
	'Cuff',
	'Like some eyes',
	'Out of practice',
	'Certain rocket engine',
	'Like St. Nick\'s "little mouth," in "The Night Before Christmas"',
	'Lacking grace',
	'Pen',
	"It's spotted in westerns",
	'With glee',
	"Plume's source",
	'State flower of New Hampshire',
	'Abscind',
	'Eugene who wrote "Wynken, Blynken and Nod"',
	'Cotton down',
	'Dynamic start?',
	'"Killing Me Softly With His Song" singer',
	'Open-mouthed',
	'Style of expression',
	'Ending with farm or home',
	'Walk stiffly',
	'Place in a Pullman',
	'Word heard in fine stores',
	'Dusk to dawn',
	'White-bread',
	'Iron-rich dish',
	'Choice for a sand trap shot',
	'Prophesy',
	'Spread out',
	'Amusingly eccentric',
	'Flying group',
	'Het up',
	'Overseas whistle blower',
	'Old as Methuselah, in a way',
	'Food for a ladybug',
	'Assignation',
	'Gnatlike insect',
	"Megalomaniac's desire",
	'Run with a hon?',
	'Sure thing',
	'Words on a coat of arms',
	"Put one's foot down",
	'Super Bowl XXXII outcome',
	'Poker ploy',
	'Restrain',
	'.946 liter',
	'Not boldly',
	'4-H participant',
	'Important element of rap lyrics',
	"Tot's transport",
	'Extraterrestrial',
	'Daub',
	'Ill-suited',
	'Hamburger, e.g.',
	'It may be static',
	'Gather gradually',
	'Record company',
	'___-dory',
	'Uniform hue',
	'Fireplace rod',
	'Dish for Oliver Twist',
	'Doubly',
	'Nasal tone',
	'Shoulder motion',
	'Doctor',
	'In the dark',
	'Futile effort',
	'Philip Morris brand',
	'Made on a loom',
	'Pertaining to base 8',
	'In the poorhouse',
	'Make faces, say',
	'Golf ___',
	'Humor not for dummies',
	'Less polite',
	'Surgical fabric',
	'Principal',
	'Commencement',
	'Set store by',
	'Mushrooms, e.g.',
	'Kind of school',
	'Hully ___ (dance)',
	'The "I" in ICBM',
	'Victory shout',
	'Needle',
	'Skeptical',
	"Teacher's charge",
	'School essay',
	'Like some goals',
	'Bone below the femur',
	'Hit the bottle',
	'Head dog',
	'Mint family member',
	'Acclaim',
	'"I ___ it"',
	'Certain knife',
	'Amusement part attraction',
	'Cinnamon unit',
	'Instant',
	'Homologous',
	'Truth, old-style',
	'Sum up',
	'November 1 honoree',
	'Vassal',
	'Exult (in)',
	'Sidewalk hazard',
	'Let in',
	'Like some walks',
	'Damp',
	'Appropriate',
	'Burn with hot water',
	'Show disdain for',
	'"Scram!"',
	'Coil',
	'Scorpion attack',
	'"When the __ breaks, the baby ..."',
	'Problematic construction site',
	'One of 7-Down',
	'Hunky-dory',
	'Drive',
	"Cowboy's greeting",
	'"Have a good time!"',
	'Authenticated',
	'Like some columns',
	'Peer',
	'Not yet scheduled',
	'Flabbergast',
	"Fisherman's take-home",
	'One in a black suit',
	"It's hoisted in a pub",
	'Just vegetate',
	'Peculiarity',
	'Casual attire',
	'It may be full of lemons',
	'Leading lines?',
	'Boris Karloff title role, with "the"',
	'Quake locale',
	'Unclear',
	'Scoff at',
	'Have as a channel',
	'Furtive fellow',
	"Slander's counterpart",
	'Move breezily',
	'With suitability',
	'Full of firs',
	'Bumbling',
	'Viva voce',
	"It's a snap",
	'Late-night show?',
	'Unfresh',
	'Expel violently',
	'Old-fashioned card game, in Britain',
	'Rear',
	'Rally',
	'React angrily',
	'Bread maker',
	'"Voila!"',
	'Informational symbol',
	'Kitty alternative',
	'Wide in the middle',
	'Period of time',
	'Bad move',
	'No-goodnik',
	'Deep ravine',
	'Safe place',
	'Pious',
	'Cast',
	'Like Atalanta',
	'Critical',
	'Foolish',
	'Unpleasant surprise',
	'Desire',
	'Malice',
	'Pipe feature',
	'Strive to stay within budget',
	"Prospector's filing",
	'Inclement',
	'Out-of-date',
	'Excite, as interest',
	'To whom "my heart belongs"',
	'Seemingly, at the start',
	'Commence',
	'Mellowing, as cheese',
	"Man's man",
	'Poppy product',
	'Forestall',
	'In a rut',
	'Split the cards again',
	'Ground cover',
	'Romance, e.g.',
	'Old-fashioned pen',
	'Search messily',
	'Matter',
	'Bring on',
	'Smash to smithereens',
	'Extract by force',
	'Coffee shop order',
	'Hold off',
	'Headwork',
	'What "-phile" means',
	'"60 Minutes" newsman',
	'Hold, as the attention',
	'Odd',
	'Fire sign',
	"Pitcher's place",
	'Improper',
	'Four-door',
	'Heathen',
	'Cast pearls before ___',
	'Deceit',
	'Perfect for kite flying',
	'Accouter',
	'"Deal with it!"',
	'Birchbark',
	'The universe on day one',
	'Break the Tenth Commandment',
	'Kind of cannonball',
	'Milk source',
	'Noon event',
	'Trumpet',
	'Homeless animal',
	'Japanese comic book genre',
	'Scrap',
	'One of a much-discriminated against minority',
	'Rapid-fire',
	'Wallop',
	'Assumed',
	"Mendelssohn's ___ in E flat major",
	'Out of bed',
	'[Not that one again!]',
	'Sievelike',
	'The old nine-to-five',
	'Perform a Thanksgiving task',
	'Unbound',
	'With low spirits',
	'All over the counter, say',
	'Mac maker',
	'Looseness',
	'Dearest',
	'"All sales ___"',
	'Bishop of old TV',
	'Otherworldly',
	'Like some mouthwashes',
	'Deft',
	'Headgear for Hardy',
	'Slip',
	"Didn't just pronounce",
	'Sports hiree',
	"Blow one's top",
	'Burn a bit',
	'$1.09 a dozen, say',
	'Give rise to',
	'Kind of magic',
	'Instant',
	'Thin and light',
	'It may go through the roof',
	'Selected',
	'It was azure-lidded, to Keats',
	'Passion',
	'Fran Drescher TV role',
	'One of the family',
	'Not thinking straight',
	'Just around the corner',
	'American-born princess',
	'Kind of machine',
	'Performed terribly',
	'Best',
	'Regular',
	'Electron tube',
	'Bravery',
	"Polygon's corner",
	'Some assassin in Japan! (5)',
	'Confuse',
	'Go after',
	'E-mail option',
	'Inclined',
	'Sour',
	"Tin Woodman's quest",
	'Sun protection',
	'Mel\'s on "Alice," for one',
	'It may involve gas',
	'Tear-jerker in the kitchen',
	'Winter hazard',
	'Wooden pin',
	'Cushion site',
	'Very friendly',
	`The part of the alimentary canal below the stomach; the intestine.`,
	'"Look happy!"',
	'Elicit',
	'Alabama native',
	"Round Tabler's weapon",
	"Colonel's insignia",
	'Dostoyevsky novel, with "The"',
	'Theda Bara, e.g.',
	'Put up',
	'Fix (in)',
	'Employee motivator',
	'Slag',
	'Bring to naught',
	'"Oh boy!"',
	'Upside-down smile',
	'Outdoor lounging area',
	'Burdened',
	'Like greenhouse air',
	'Power ___',
	'A serous fluid',
	'Enlighten',
	'Strength',
	'Change, as a clock',
	'Short stay',
	'Relish',
	'Winnings',
	'Gaseous mist',
	'Bit of earthenware',
	'Pen',
	'Cheerful',
	'Disinclined',
	'Refuse',
	'Get home safely?',
	'Mysterious',
	'Snake spit',
	'Kind of pad',
	"Classic kids' game",
	'Mountain dew producer',
	"It's put away for winter",
	'Being a copycat',
	'Hardly retiring',
	'Bronco buster',
	'Misanthrope',
	'Craze',
	'Came to',
	'Muscle',
	'"A Modest Proposal" writer',
	'Banishment',
	"Hazel's cousin",
	'Like a four-leaf clover',
	'Less constrained',
	'Like venture capital investments',
	'Basic Halloween costume',
	'Buy-one-get-one-free item?',
	'Like some landings',
	'Hoisting device',
	'Booby trap',
	'Hospital cry',
	"Roulette player's opponent",
	'Common cleanser',
	'More subtle',
	'Pitch suddenly',
	'Ennoble',
	'Concerning',
	'Streetwise',
	'Antidote target',
	'Part of a military uniform',
	'Snooped',
	'Do parquetry',
	'Sap',
	'Like young Abe Lincoln',
	'Salad ingredient',
	'Pizzeria patron',
	'Circumvent',
	'Full course',
	'Long Branch Saloon proprietress',
	'Ball in the game pétanque',
	'Idiot',
	'Basic belief',
	'Set down',
	'Seek to influence',
	'Luxurious',
	'Watch',
	'The Dow, e.g.',
	'Go on and off, as a traffic light',
	'Held (to)',
	'Reservation',
	"Infant's illness",
	'Post-toast sound',
	'Like a melon',
	'Rocket section',
	'Rot',
	'Moxie',
	'Ace',
	'Mine passage',
	"Bo-peep's staff",
	'Innocent',
	'Popular wedding gift',
	'See 53-Across',
	'"Wheel of Fortune" purchase',
	"Troll's cousin",
	'Smuggled',
	'Cake decoration',
	'Like hedgehogs',
	'Hardship',
	'Escargot',
	'Taken wing',
	'Very enthusiastic, as a fan',
	'Text',
	'Express gratitude to',
	'Plant in Flanders fields',
	'Stop being obstinate',
	'Cereal stuff',
	'Like stuff in the back of the fridge, maybe',
	'Hardly hip',
	'Prepare to propose',
	'Keep tabs on',
	'Ace of clubs?',
	'Put down forcibly',
	'Short and stout',
	'Not so ruddy',
	'Used colorful language',
	'Steel support for concrete',
	'Take a breather?',
	'Sloppy-landing sound',
	'Small handbill',
	'Like rhinos',
	'With 18-Down, home canning items',
	'"Nothing ___!"',
	'Fresh air, slangily',
	'Sufficiently',
	'Grinder',
	'Egg maker',
	'Assail',
	'File',
	'Steep',
	"Like Mozart's flute",
	'Cease-fire',
	'Show off',
	'On the ___ (not working)',
	'Pronouncement',
	'Handle a baton',
	'Poem',
	'Cousin of a camel',
	'Consumed',
	'Where the buffalo roam',
	'Egg beater',
	'Shack',
	'Recovery regimen, for short',
	'Long-tailed parrot',
	'Greek letter',
	'State oratorically',
	'Dash',
	'Bar offering',
	'Eager',
	'Stinky',
	'Genius',
	'Pal',
	'Hitting sound',
	'Offshoot',
	'Kind of bar',
	'Feeling',
	'Boatyard',
	"Drillmaster's command",
	'Throng',
	'Ann ___, Mich.',
	'With festiveness',
	'Like some colognes',
	"Microscopist's reagent",
	'Dawdle',
	'Word of grace',
	'Acclaim for Pavarotti',
	'Overcharged',
	'Library info',
	'Schoolbag item',
	'Place to post notices',
	'Towhead',
	'Boredom',
	'Cake part',
	'Not fixed',
	'Cheap',
	'Accompanying music',
	'Doll',
	'Striped critter',
	'Carrier in a canal',
	'Chum, to a Brit',
	'Further down',
	'Support person',
	'Clinched an agreement, perhaps',
	'Missouri or Delaware',
	'In on, with "to"',
	'Some kind of a nut',
	'Search, as for weapons',
	'Beat it!',
	'Under way',
	'Sky-blue',
	"Bob's companion",
	'Spirit',
	'Unflawed',
	"Fielder's aid",
	'Plait',
	"Sub's eye, for short",
	'In a sardonic way',
	'Itinerant',
	'Ore analysis',
	'Arctic, for one',
	'Rarity for a century plant',
	'Furious',
	'Subsequently',
	'No longer asleep',
	'Smooth',
	'Jalopy',
	'Resided',
	'Old schoolhouse item',
	'Directly',
	'Completely reliable',
	'Floor',
	'Old TV series based on a cartoon',
	'Spin imparter',
	'Laugh-filled',
	'Classroom accessory',
	"General Motors' birthplace",
	'Stir from slumber',
	'Kind of engineer or service',
	"Postcard's picture, often",
	'Chill, so to speak',
	'Nightclub charge',
	'Full of pep',
	'Tree with triangular nuts',
	'Breakwater',
	'Heaven',
	'Song part',
	'Time after time',
	'Warehouse roller',
	'Ice skating figure',
	'Wild card',
	'Because',
	'News subject',
	'Follow',
	'Divert',
	'One who works under pressure',
	'Brainteaser',
	'Deserving the booby prize',
	'Win all the games',
	'Back way',
	'Statement of belief',
	'Modern cartoon genre',
	'Like lettuce or spinach',
	'Kind of buddy',
	'Numbskull',
	'Glower',
	'A little overweight',
	'Give up',
	'Group that has its own organ',
	'Underwent',
	'Ray, in a way',
	'Expenditure',
	'Hold up',
	'Unwelcome water on a ship',
	'10 on a scale of 1 to 10',
	'Necklace fastener',
	'Collar',
	'How some arguments are conducted',
	'Roll in the aisles',
	'Screening device',
	'Urban area',
	'Intended',
	'Kool-Aid flavor',
	"Lariat's end",
	'Built to take it',
	'Shrank (from)',
	'Dixie talk',
	'"She loves me, she loves me not" flower',
	"Tiler's need",
	'Swagger',
	'Taken, slangily',
	'Sign of spring',
	'Pain in the neck',
	'Virgil creation',
	'Foxy lady',
	'Hue and cry',
	'Not at all cool',
	'Engine sound',
	'Unschooled, as an artist',
	'Sand bar',
	'Marabou, for one',
	'Clean up',
	'Familial nickname',
	'Common element of 20- and 56-Across and 10- and 27-Down',
	'Best rate',
	'Chutzpah',
	'___ Banks, N.C.',
	'Like some friends',
	'Chin smoother',
	'Choice',
	'Put out',
	'Hint at',
	'Beg off',
	'Floor or ceiling',
	'Sanctuary',
	'Carp',
	'Take an oath',
	'Crunching sound',
	'Long green',
	"Auctioneer's aid",
	'Part of a train',
	'Fashionable shop',
	'Elbow',
	"Sheik's bevy",
	'Spiel',
	'Kind of statement',
	"Iris's center",
	"Get straight A's, e.g.",
	'Obdurate',
	'Log home',
	'Open, as a jacket',
	'Wicked "Snow White" figure',
	'Steelhead, e.g.',
	'Nodule',
	'Home base, in sci-fi',
	'Tempest',
	'"Wait ___ Dark"',
	'VCR',
	'Computer command',
	'Tot',
	'Ratify',
	'Like some keys',
	'Old-time comedian Arbuckle',
	'Sled dog',
	'Plucky',
	'___ mignon',
	'Ooze',
	'Flash',
	'"Don\'t __ on me" (Revolutionary flag motto)',
	'Incredible bargain',
	'Buick model',
	'Talk show chatter',
	'All possible',
	'Not pellucid',
	'Quota',
	'Fern fruit',
	'Loading apparatus',
	'Healthy, plump, cheerful, and lively',
	'Private',
	'Playful aquatic animal',
	'Romantically, vis-à-vis lighting',
	"Carpenter's tool",
	'Poison ___',
	'Glazed food item',
	'Circus prop',
	"Gladiator's place",
	'Kind of music or lightning',
	'Second-stringer',
	'Imagination',
	'Vile',
	'Precious one',
	'One way to be knocked',
	'Veranda',
	'Down Under dog',
	'Print tint',
	'Stroll',
	"Like a con artist's business",
	'Communion offering',
	'Monastery figure',
	'Hold sway',
	"Holstein's home",
	'Quaint pen',
	'Pen name',
	'The Brady kids, e.g.',
	'Jerusalem artichoke, e.g.',
	'Wind danger',
	'Propose',
	'Hold to a zero score',
	'Fancy home',
	'Meat cut',
	'Little digit',
	'Carnival oddity',
	'Any-way link',
	'___ friends',
	'poopy',
	'Carapace',
	'___-be',
	'Sign of stagnation',
	'Supersized',
	"Browning's Ben Ezra, e.g.",
	'Kind of column',
	'Tickle',
	'Like an Afro',
	'Thicket',
	'Faint',
	"Bowie's weapon",
	'Something under a tired eye, maybe',
	'"My Fair Lady" scene',
	"Pilot's command",
	'Queen topper',
	'Kind of sprawl',
	'Nasty',
	'Kind of station',
	'Put up with',
	"Walter Trampler's instrument",
	'Eastern prince',
	'Float accessory',
	'Ripsnorter',
	'Market problem',
	'Aggregate',
	'The hot corner',
	'Take in',
	'Teach one-on-one',
	'Old station wagon, in slang',
	'This may be found on a jacket',
	'"Good ___!"',
	'Bygone music genre',
	'The place',
	'Pert',
	'Place for an umbrella',
	'Spa feature',
	'Work in panels',
	'Aware, with "in"',
	'Undesirable',
	'Social position',
	'Just touch',
	'Put (out)',
	"Monk's robe",
	'Gamete producer',
	'Under the table',
	'Projecting part',
	'Like tabloid writing',
	'Product of Bethlehem',
	'Bisect',
	'Word before "beware!"',
	'Naugahyde coating',
	'Practical',
	'Nose',
	'"Penny wise, pound foolish," e.g.',
	'Fret',
	'Palatable',
	'Brighton pub',
	'Vocation',
	'Bunting or sparrow',
	'Pale',
	'Relating to form',
	'Haggard',
	'Part of a bulb',
	"Do a legislator's job",
	'Dress up',
	'Friars Club event',
	'Tiny bit',
	'Role for Valentino',
	'Girl, informally',
	'Kind of work',
	'Prier',
	'Do',
	'Slight amount',
	'"GoodFellas" group',
	'Figure at a roast',
	'Collection',
	'Downward, in a way',
	'Hardly stimulating',
	'Toast topper',
	'Move stealthily',
	'Gut-wrenching feeling',
	'Like some pregnancies',
	'Humble',
	'Colgate rival',
	'Worry',
	'Internet prefix',
	'Like a bunch',
	'Belated',
	'Teacher in a turban',
	'Part of a spool',
	'Prepare, in a way',
	'Kind of motel',
	'Thumb',
	'Latter-day Saints leader Brigham',
	'True up',
	'Primed',
	'Palm leaf',
	'Subway support',
	'Blender setting',
	'Kingdom',
	'Stage or stadium, say',
	'1978 disaster film, with "The"',
	'Submit',
	'1995 Pitt flick',
	"Beautician's device",
	'Bedside book',
	'Without any pizazz',
	'Guzzled',
	'Tart',
	'Thrilling',
	'Head of Thermopylae?',
	'Self-appointed committee with political aims',
	'Sprite',
	'Said à la the Raven',
	"Employee's reward",
	'Ten Commandments word',
	'Tubular pasta',
	'Edit',
	'Fact or factoid',
	'Physical stature',
	"Nero's instrument",
	'Storage space',
	"Nixon's running mate in 1960",
	'Litigation',
	'Violate a treaty, perhaps',
	'Pinkish color',
	'Japanese noodle dish',
	'Mary of the comics',
	'One of 150',
	'Deduce',
	'Impossible to miss',
	'Giuliani, e.g.',
	"Like Mork's spaceship",
	'Bit of a waltz',
	"Grammarian's concern",
	'Aplomb',
	'Lustful',
	'Toss',
	'Short-sheeting a bed, e.g.',
	'Suspicious',
	'Kind of fairy',
	'Old-time anesthetic',
	'Herd',
	'Goldbrick',
	'Mowed strip',
	'Limited work assignment',
	'Indefinite wait',
	'Sired, in biblical times',
	'Put on, as glue',
	"Jive talkin'",
	"Gypsy's deck",
	"Scientific breakthrough of the 30's",
	'Set of beliefs',
	'Informed',
	'Church law',
	'Tab neighbor',
	'Track official',
	'Charter member?',
	'Emergency room supply',
	'"Eli\'s Coming" singers __ Dog Night',
	'Hearty dinner entree',
	'Of the upper hipbone',
	'Dodge',
	'Weaken',
	'Litter member',
	'Kind of colony',
	'Ceiling supporter',
	'Cadbury mascot',
	'Octagon or oval',
	'Sire',
	'Roller',
	'Proficient',
	'Public relations gambit',
	'Purloined',
	'Uris novel',
	'Task',
	'Bit of serendipity',
	'"The game is ___": Holmes',
	'Balloon',
	'Cow',
	'Thick',
	'Prank',
	'Look of contempt',
	'Kind of shorts',
	'Larger than extra-large',
	'Suddenly leap (at)',
	'1982 Michener epic',
	'Profit',
	'Strapped',
	'Impolite sound',
	'Like a dog',
	'Vamp',
	'Food often cut in eighths',
	'Shell',
	'Adagio, for one',
	'Sag',
	"Batter's position",
	'Authoritative text',
	'Put (down), as money',
	'Run ___ of (violate)',
	'___ operas (Gilbert and Sullivan works)',
	'At quite an incline',
	'Quick',
	"Vampire hunter's weapon",
	'Roost, so to speak',
	'Jack',
	'See 32-Down',
	'Developed',
	'Recurring subject',
	'Overhead shot',
	'Tumult',
	'Blinding light',
	'Leave, with "off"',
	"Like many 90's trousers",
	"Al Capp's Pansy Yokum",
	"Will-o'-the-wisp locale",
	'As a companion',
	'Ball game since 1823',
	'Vegas transaction',
	'Unlicensed physician',
	'Play catcher, say',
	'S-shaped',
	'Ledger entry',
	'Something that might make the fur fly?',
	'Use Rollerblades',
	'Beethoven\'s "Choral" Symphony',
	"Knights' competition",
	"Lady's lover",
	'Reject',
	"Olympian's prize",
	'Prefix with surgery or transmitter',
	'Malcontent',
	'Meat cut',
	'Absorb',
	'Point of depression',
	'Sugar source',
	'Like a good lounge chair',
	'Send, as payment',
	'Surly',
	'Benzocaine, for one',
	'Extreme amount',
	'Business bigwig',
	'"Go get it, Fido!"',
	"Idealist's need",
	'Like some buckets',
	'Lit',
	"Enough to sink one's teeth into",
	'Faux pas',
	'In a demure manner',
	'Indy entrant',
	'Search for prey',
	'One available for the taking?',
	'Back of a boat',
	'Where "e\'en" is seen',
	'Uncertain',
	'Sound from an aviary',
	'Midsection',
	'High riser',
	'Search blindly',
	'Rack and ruin',
	'Stooge',
	'"No kidding"',
	'Quota of winks',
	'Saturn or Mercury',
	'"I surrender!"',
	'Sound of a basket',
	'Testator',
	'Primp',
	'Angle on a gem',
	'Arboreal animal',
	'Unedited version',
	'Declivity',
	'Bother',
	'Shoptalk',
	'Like some prospects',
	'Simple song',
	'Frizzed',
	'Lebanese tree',
	'Gloomy tune',
	'Adult',
	'Motley crew',
	'Openly salivate',
	'Remove the hull of',
	'Underground chamber',
	'Pickle flavoring',
	'Standard',
	'Quip, part 3',
	'Point of interest',
	"Dentist's directive",
	"__'s Hill (Battle of Bunker Hill site)",
	"Brit's reply in agreement",
	'Rub the wrong way?',
	'Where the loot gets left',
	'Aerial view provider at sports events',
	'Consider appropriate',
	'Mr. Hyde, for one',
	'Work done on the premises?',
	'Like Jack Benny, famously',
	'Skip over',
	'Set',
	'Made-up',
	'Of the kidneys',
	'p., as in Plymouth',
	'Obstreperous',
	'"Fiddlesticks!"',
	'Four-alarmer, e.g.',
	'Representative',
	'Sworn body',
	'Short-winded',
	'"When pigs fly!"',
	'Call off a takeoff',
	'Cursor mover',
	'Filthy-dirty',
	"Pacer's burden",
	'Intensely hot',
	'Press',
	'Spare holder',
	"Brewer's need",
	'Fair',
	'___ cabbage',
	'Resell at a profit',
	'Teensy-weensy',
	'Autumn beverage',
	'Queensland native',
	'Comforter',
	'Direction in music',
	'Doughnut filler',
	'___ Tuesday',
	"Bar's partner",
	'In the future',
	'Lady with a title',
	'Hot coal',
	"Boxer's stat",
	'In a distinguished way',
	'Drain',
	'The "tacho" in tachometer',
	'Flamenco band The ___ Kings',
	'Persist',
	"Artist's wear",
	'Great fear',
	'Go with the flow?',
	'Stick with a pin',
	'Key letter',
	'"Jaws" setting',
	'Tenuous',
	'Remain in an uncertain state',
	'Part of a candlelight ceremony, maybe',
	'Belt',
	"Clerics' confab",
	'Barely visible',
	'Visit again and again',
	'Ground meal',
	'Conduct, in a way',
	'Dry out',
	'Ill-tempered woman',
	'What a will, e.g., may indicate?',
	'Employed busily',
	'"Charmed" subatomic particle',
	'Like Paul Bunyan',
	'Wouk work',
	'Like a candle',
	'Uncomplaining',
	'Uneven',
	'Barrage',
	'See 35-Across',
	'Full of feeling',
	'Impudent girl',
	'Poolside turban',
	'Bee product?',
	'"Look out ___!"',
	'"That\'s it!"',
	'Gossamer',
	'Full of chutzpah',
	'Teacake',
	'Brown',
	'Chart holder',
	'Flippant',
	'Esteem',
	'Enliven',
	"A feather in one's cap",
	'Beat',
	'High-pitched',
	'Ribald',
	'Pie cuts, essentially',
	'Brain protector',
	'Quack',
	'Progeny',
	'Bar selection',
	'Jim-dandy',
	"A British laboratory's new cell phone is powered by this",
	'Loquacious, in slang',
	'Court TV coverage',
	'"The Turn of the Screw" girl',
	'Like certain dentures',
	'Gate holder',
	'Isle of ___',
	'Milder version of Limburger cheese',
	'Hear again',
	'Christmas decoration',
	'Stick-on',
	'Park feature',
	'Rough cabin',
	'Tenets',
	'Go-getter',
	'Hold off',
	'Clearheaded',
	'Of the eye',
	'Town ___ (early newsman)',
	'In competition',
	'Land rover',
	'"Peter and the Wolf" bird',
	'Swimmer in the Congo',
	'California hockey player',
	'Less moist',
	'Like Falstaff',
	'Taps producer',
	'Lion-colored',
	'Classroom supply',
	'Wedding reception, say',
	'Not pale, as a complexion',
	'Step on it',
	'Winter wear',
	'Diabolical',
	'Cry out',
	'Of neap and ebb',
	'Kind of fund',
	'"There\'s Something About Mary" fluid',
	'Blowing',
	'Name for a cowpoke',
	"TV's ___ Jessy Raphael",
	'Dome home',
	'Like Dilbert',
	'Watch bearing',
	'Excelled',
	'Moby-Dick, for one',
	`a thin piece of mucosal tissue that surrounds or partially covers the external vaginal opening`,
	'Wrong',
	'Bach offering',
	'Jostle',
	'Tidbit',
	'Wuss',
	'Cardiff citizens',
	'Chocolate ___',
	'Short-winded',
	'Urbane',
	'Entire spectrum',
	'Turned',
	'Circumnavigator Sir Francis',
	'No longer a slave',
	'Burning',
	'Polo or tee',
	'Thin mortar',
	'Not as expected',
	'Split for a church',
	'Checks on clothing',
	'"Person" in a crash test',
	"Witch's ride",
	'Duck ___',
	'British flashlight',
	'A McCoy, to a Hatfield',
	'Once more',
	'Making even',
	'Like Dennis the Menace',
	'Take in or let out',
	'Rubbernecker',
	'Lofty',
	'Moral element in literature',
	'Vow taker',
	'Laud',
	'Style of furnishing',
	'Stamp or coin collecting, e.g.',
	"Beauty's swain",
	'Dialect',
	'Out-and-out',
	'"One of ___ days, Alice..."',
	'Beethoven\'s "Pastoral" Symphony',
	'Waker-upper',
	'Clear',
	'Thomas Gray work',
	'Spirit',
	'Flute player',
	'Like snakeskin',
	'Chide, as a child',
	'Substantial',
	'Peeper',
	'Like smokestacks',
	'Ear part',
	'Complaining',
	'Virgule',
	'Temblor',
	'Dive',
	'Thoroughly searched',
	'Bluenose',
	'Backbreaking',
	'Brandish',
	'Wife abroad',
	'Catch cowboy-style',
	'Indian corn',
	'Kind of oil',
	'It can go in brackets',
	'Spending time?',
	'Great ___ Mountains National Park',
	'Swing and a miss',
	'Lilac, e.g.',
	'Clearing',
	"Lightened one's billfold",
	'Chandelier pendant',
	'Tend the hearth',
	'More mellow',
	"Satellite's path",
	'Drink served with marshmallows',
	'___ trip',
	'Soil improver',
	'Silence',
	'Put on ice',
	"Brat's look",
	'Amiss',
	'Like many a jalopy',
	'With ears pricked',
	'Newly waxed',
	'Send',
	'"Jurassic Park" mosquito preserver',
	'Undiminished',
	'Funny feeling',
	'Dot on a monitor',
	"Like 19-Across's expeditions",
	'Boardwalk buy',
	'Fencing weapon',
	'Soccer shoe',
	'Tropical fruit',
	'Cuban dance',
	'Bloated',
	"Colt's counterpart",
	'One of the Baldwin brothers',
	'Dog restraint',
	'Influence',
	'Monkey or pony',
	'Shaped like a May apple',
	'Diamond side',
	'__ dog (zesty frankfurter)',
	'Benjamin Moore product',
	'Eye enhancer',
	'Antique shop item',
	'Full of four-letter words',
	'Television minus the vision',
	'Weave in and out',
	'Epigrammatic tale',
	'Disguise',
	'This may be contemplated',
	'Jet',
	'Genoese creation',
	'Mild, as weather',
	'Word with card or flood',
	'Single',
	"Baseball's Wynn",
	'Agitate',
	'Like unkept yards',
	'Perplex',
	"Renter's paper",
	'Like Oscar Wilde',
	'Like a milquetoast',
	'Parody',
	'More rational',
	'Mixture',
	'Tortilla chip topper',
	'Not too brainy',
	'Witchlike',
	'Frenzied',
	'Proclaim noisily',
	'Short news bit',
	'Part of a place setting',
	'Explore',
	'Crinkly cloth',
	'Special skill',
	'Compel',
	'First showing',
	'Court demand',
	'Waste maker',
	'Drill targets',
	'Instrument',
	'Ream',
	'With aloof disdain',
	"It's a piece of cake",
	'Mint bar',
	'Create friction',
	'Panel member',
	'Drink for Drac',
	'Dwelling place',
	'Kind of pillow',
	'Agreement',
	'Come about',
	"Wasn't vigilant",
	'March',
	'Two-for-one?',
	'Drain',
	'Break down, in a way',
	'Be transformed',
	'Desert flora',
	'Hardly elegant',
	"Embroiderer's purchase",
	'Fiend',
	'Dour',
	'Take over, in a way',
	"Get one's feet wet",
	'Unclear',
	'Nicotine source',
	'No-cal drink',
	'Not evenly padded, as a mattress',
	'Campus offices: Abbr.',
	'Popular watch brand',
	'Restrict',
	'Cat, informally',
	'Virile',
	'Bridal walkway',
	'Small boat',
	'Foundation',
	'One way off a ship',
	'Brink',
	'Bungle',
	'Rush-hour pace',
	'Stinky',
	'Killed',
	'Like some measures',
	'Up, as the ante',
	'Destroy',
	'Conduct',
	'Impose',
	'Minor role',
	'Secondary to',
	'Thespian',
	'Variety show',
	'Better Business Bureau subject',
	'Part woman, part bird creature',
	'Big news exclusive',
	'Advance oneself',
	'Send elsewhere',
	'Bygone',
	'Bob Cratchit, e.g.',
	'Prohibit',
	'Correspond',
	'Moral principle',
	'Stone mound',
	'Prom dress material',
	'Grave plunderer',
	'Like western Massachusetts',
	"Tanker's cargo",
	'Disjointedly',
	'Plate of salmon, e.g.',
	'On in years',
	'No-frills',
	'Kind of whale',
	'Salty',
	"Brothers' keeper?",
	'Nick at Nite offering',
	'Mission',
	'Like toast',
	'Spring',
	'Comport with',
	'Formulated',
	'Hotel booking',
	'Restless',
	'All alternative',
	'Deli item',
	"Riddler's challenge",
	'Vast',
	'If A = B and B = C, then A = C, e.g.',
	'Swiss ___ (vegetable)',
	`a Latin word meaning literally "head"`,
	"Wasn't upright",
	'Raspy',
	'A mummy may have one, perhaps',
	'Feeling puffed up',
	'Playground equipment',
	'Think a thought',
	'Smack',
	'Southern constellation',
	'Okra stew',
	'Underground worker',
	'Village center',
	'Gulf',
	'Biochemical compound',
	'What debaters debate',
	'Kind of plate',
	'Touch lightly',
	'Stretch',
	'Subway artwork',
	'Differently ___ (having other skills)',
	"Equestrian's garb",
	'Not like a milquetoast',
	'Manufacturer',
	'Somewhat dark',
	'Swimming',
	'Loose-limbed',
	'Stomach',
	'DJ ___ Jeff',
	'*Evenly split',
	'Taste, e.g.',
	'Elephantine',
	'Rude and sullen',
	'8 1/2" x 14"',
	'Deadly',
	'Hold back a year in school',
	'Set in motion',
	'Cut back',
	'Slight',
	'What italics do',
	'Knock, with "at"',
	"Doughnut's shape",
	'Fool',
	'Group of quails',
	'Spiteful one',
	'Spoken for',
	'Upright',
	'Fashion',
	'Because of, with "to"',
	'It might get you a ride',
	'Way in',
	'"Sic semper tyrannis" shouter',
	'Nay-sayer, perhaps',
	'Rebuke',
	'Mischievous',
	'Black',
	'"No" vote from a horse?',
	'1/60 fluid dram',
	'Breakfast offering',
	'Injured indelicately',
	'Shill',
	'"Behold!"',
	'Shackle site',
	'Traffic director',
	'Like cooked oatmeal',
	'Cayugas or Senecas',
	'Knock off',
	'Athirst',
	'Beginning',
	'Boardroom easel display',
	'Stranger',
	'___ cotta',
	'Outré',
	'Heard in court',
	'Typewriter sound',
	'Do a salon job',
	'It might make a bad lie',
	'Consider the pros and cons of',
	'Not abridged',
	'Serve, as stew',
	'Dismantle',
	'Vessel',
	'Without',
	'Rather risky',
	'Giant',
	'Astronaut in 1996 news',
	'Clergyman',
	'Slip cover?',
	'You can dig it',
	'Wanderer',
	'Noodles',
	'It may be pulled',
	'Olympics sight',
	'Plunge suddenly',
	'Removed',
	'Spectacle',
	'Penniless',
	'Moist-eyed',
	'Perot prop',
	'A mile a minute',
	'Going on and on',
	'Very, very thin',
	'Shunned one',
	'Hardly unconcerned: Var.',
	'Expansion of a sort',
	'Enjoy',
	"Carpenter's device",
	"Like James Brown's music",
	'Unlike flat beer',
	'Like locoweed',
	'Stigmatize',
	"Carpenter's gadget",
	'Grayish',
	'Isolated hill',
	'Practice',
	'Rubbish',
	"It's strengthened by 56-Across",
	'Caruso was one',
	'Crustaceans eaten by whales',
	'Not so good',
	'Pulitzer category',
	'"Laughing" animal',
	'Use your brain',
	'Five-to-one, e.g.',
	'Army attack helicopter',
	'Pesto ingredient',
	'Rugby formation',
	'Like many students at school',
	'Drop a dime, so to speak',
	'Legal setting',
	'Caravan beast',
	'___ positive',
	'Was informed of',
	'Heavenly host?',
	'Bee quest?',
	'Sullen',
	'Pound',
	'Gershwin song of 1926',
	'Postembryonic',
	'Bit of parsley',
	'Vertebra locale',
	'Whoop',
	'Academy student',
	'Computer shortcut',
	'Hard to pin down',
	'Mythical goat/man',
	'Harder to find',
	'Pig out',
	"That's the way it goes",
	'Cuckoo',
	'Sprang',
	'Out of place',
	'Alley "oops"',
	'Biblical gift',
	'Board measure',
	'Sub detector',
	'Radio station need',
	"Munchhausen's title",
	'Kind of pitch',
	'Seesaw',
	'Fire starter',
	'Contradict',
	'Single-masted vessel',
	'Boot out',
	'Slew',
	'Farm machine',
	'With 63-Across, pretty good',
	"What's up at Rand McNally?",
	'Symbol of thinness',
	'Meager',
	'Bell or whistle',
	'Flooded',
	'Potential diet-breaker',
	"Grouch's look",
	'Easily broken',
	'Implication',
	"It's neither here nor there",
	'Field enclosure',
	'"Psycho" setting',
	'Pound part',
	'Inflict',
	'Celebrate',
	'Bird holder',
	'Former',
	'Prepared to propose, perhaps',
	'The "voice" in Bloch\'s "Voice in the Wilderness"',
	'Eccentric type',
	'Fix, as software',
	'Battery part',
	"Moriarty's specialty",
	'Soothing ointment',
	'Reconnoiterer',
	'Permeate',
	'Little finger',
	'Barrel piece',
	'Hard to pin down',
	'Steadying wedge',
	'Quote, part 6',
	'Broadcasting feed',
	'Precious ___',
	'Show how',
	'Chin indentation',
	'"Mending Wall" poet',
	'Jumbo shrimp',
	"Pirates' plunder",
	"Chubby Checker's dance",
	'Sleep disturber',
	'Leave without paying',
	'Town square',
	'Rock shelf',
	'Fine-tune',
	'Part of an American plan, at a hotel',
	'Research money',
	'Battlefield V.I.P.',
	'Breakfast sizzler',
	'Dish alternative, maybe',
	'More than a scuffle',
	'Hardly strutted',
	'Grating',
	'Discussion opportunity',
	'Go on and on',
	'Common door sign',
	'Snail trail',
	'Trumpet',
	'Some like it hot',
	'Group of witches',
	'Protuberance',
	'More correct',
	'Vindictive anger',
	'Play for time',
	'Letter opener?',
	'About the line of rotation',
	'More refined',
	'The Post or News, e.g.',
	'Be behind',
	'Recess',
	'___-mouthed',
	'Power',
	'Parachute material',
	'Chubby',
	'Party-making',
	'Swing wildly',
	'Kind of cross',
	'It may be found in an elevator',
	'Vine fruit',
	'Show fear',
	'Put up',
	'Savage',
	'Having attractive gams',
	'Petty criticism',
	'Strength',
	'Lodge resident',
	'Small change',
	'Skittish',
	'Come-from-behind attempt',
	'Dark area',
	'Chilling',
	"Web user's need",
	'Hollywood figure',
	'Birdlike',
	'One of 7-Down',
	'Luxurious sheet material',
	"Gin's partner",
	'Arctic fur',
	'Haughty response',
	'Furious',
	'___ raving mad',
	'Declared suit',
	'Lightheaded',
	"Don't waste",
	'Forbidden',
	'Work around',
	'"And I ___..."',
	'Tasmanian ___',
	'Compare',
	'Misleading interpretation',
	'More bright, as colors',
	'Military wear',
	'Bruit (about)',
	'Pancreas, e.g.',
	'Passed out',
	'Rifle strap',
	'Kind of mill',
	'Soap ___',
	'Chicken cut',
	'South Pacific nation',
	'Distress signal',
	'Twisted',
	'Justice replaced by Ginsburg',
	'Cumbersome',
	'Liszt piece',
	'Gym apparatus',
	'Around',
	'Rice ___',
	'Where work may be waiting',
	'Effervescent',
	'Silo contents',
	'Put forth',
	'Sudden swelling',
	'Flash of light',
	'"Memphis ___" (1990 war film)',
	'Blast',
	'Puppy love',
	'Part of a balanced diet',
	'Overly sentimental',
	'Selfish sort',
	'Plot of land',
	'Sheeplike',
	'Like some punk hairdos',
	'Open',
	'Full of cattails',
	'Crud',
	'Outburst',
	'Nautical order',
	'Cha-cha cousin',
	'"Oh, sure"',
	'Knight noise',
	'Kind of account',
	'Unit of light',
	'Held up',
	'Scare',
	'See 10-Across',
	'Yellowish-brown',
	'Wood-turning tool',
	'Diamond weight',
	'Kitchen utensil',
	'Smutty',
	'With subterfuge',
	'Attach',
	'Solder, e.g.',
	'"___ so!"',
	'Blind followers',
	'Tightly curled',
	'"___ Bully" (1965 hit)',
	'Purple shade',
	'Threw',
	'Cruise in style',
	'Overexposed to the sun',
	'Shrink with fear',
	'Main impact of an attack',
	'Filth-covered',
	'Winding',
	'Shrewd',
	'Certain cycle',
	'What turns 19 into 21?',
	'Start of many criminal case names',
	'Understanding',
	'Whitish',
	'Plains roamers',
	'White collar crime',
	'Yellowish-red',
	'Make a temporary stitch',
	'Back pocket liquor bottle',
	'Waffle',
	'Kind of show',
	'Swagger',
	`Like a skeleton`,
	'Stylish auto',
	'Give',
	'Hate',
	'Longtime G.E. chief with the best seller "Jack: Straight From the Gut"',
	'Plow part',
	'Close',
	'Skein components',
	'Scrooge',
	'Feature of a Friars Club meeting',
	'Symbol of a lingering scandal',
	'Cassius and company, in "Julius Caesar"',
	'Parasite',
	'Just off',
	'A dime, dollarwise',
	'Texas state tree',
	'French right',
	'Holy chalice of legend',
	'Replicate',
	'Semblance',
	'Nobel-winning Bunche',
	'Albeniz\'s "___ in D"',
	'Fussbudget',
	'Farrier, e.g.',
	'Necessity at a golf club',
	'Check casher',
	'Printing flourish',
	'Hang',
	'A to E, musically speaking',
	'Hit bottom?',
	'Shiny coating',
	'Divvy up',
	'Transport',
	'Olympic vehicle',
	'Bug',
	'Snappish',
	'Plains home',
	'In toto',
	'Like some shipping rates',
	'Subway',
	'Mulligatawny ingredient',
	'Super-duper',
	'Bluegrass player',
	'Hypothetical physics particle',
	'Automobile headlight holder',
	'Come to mind',
	'Mountain range',
	"Like Fran Drescher's voice",
	'Like hot fudge',
	'Certain office worker',
	'Steady',
	'Put to rest',
	`___ hair, not usually public`,
	'Deep black',
	'Beg',
	'Grind',
	'Like some pie crusts',
	'Chew (on)',
	'Without much intelligence',
	'Making (out)',
	'Addams Family member',
	'Go furtively',
	'"Faster!"',
	'Embezzlement, e.g.',
	'Less woolly, perhaps',
	'African tribesman',
	'Alternative to Russian',
	'Extort',
	'Fruit at the bar',
	'Beach',
	'Family head',
	'Stood still',
	'Comparatively modern',
	'Fashion',
	'Lodge member',
	'Caper',
	'Go under for the third time',
	'Meat avoider',
	'Popular newspaper column',
	'Aquarium staple',
	'Coalition',
	'Jimmy',
	'Hampshire hauler',
	'Screen presentation',
	'Driver of a 72-Down',
	'Like some priests of old',
	'Squeeze (from)',
	'Veridicality',
	'Disney dwarf who "never had anything to say"',
	"Headhunter's equipment",
	'Hollered',
	'Ring',
	'Sidekick',
	'Reeked',
	'Not bold',
	"Baker's dozen?",
	"Meter reader's reading",
	'Copter part',
	'Highly skilled',
	'Pinup feature',
	'Starbucks serving',
	'Broom Hilda, e.g.',
	'"The Brady __" (show on which Carol is the mom)',
	'Gross out',
	'Verdi\'s "___ Chorus"',
	'Melodramatic',
	'Parkers feed it downtown',
	'Gravy ingredient',
	'One way to be in love',
	"Cut's partner",
	'Street fight?',
	'Famous',
	'Molten rock',
	'Chicken house',
	'John Lennon hit',
	'Minimal swimwear',
	'Right or left',
	'Far from tan',
	'Soft',
	'Massage',
	'Brief attempt',
	'Like some transit',
	'Repeated word in "The Trolley Song"',
	'Emotional heat',
	'Tee off',
	'Disney star',
	'Send',
	'Folk or rap, e.g.',
	'Things',
	'Clean up, in a way',
	"It's added to the bill",
	'Center of activity',
	'Large book',
	'Frame',
	'Page 2, usually',
	'Subdue',
	'"Sleeping Beauty" fairy',
	'Like envelope seals',
	'One of the Seven Dwarfs',
	'Freshly',
	'Fastidious',
	'Holdover',
	'Jelly fruit',
	'Threadbare',
	'Falsify, in a way',
	'Biggest bone in the body',
	'Happy sound',
	'Strength',
	"Suspect's need",
	'Complaint',
	'Of no importance',
	'"Holy smokes!"',
	'Cloth fold',
	'Bit of dandruff',
	'Con',
	'Natural ladle',
	'Coffee or cocoa',
	'Guitar sound',
	'29-Across genus',
	"Thief's secret",
	'Condemn openly',
	'Older but ___',
	'Undemocratic government',
	'Cap feature',
	'Intimidate',
	'Detritus on the side of a mountain',
	'Incite',
	'Be in store for',
	'Squeeze',
	'"___ Honey Are You?" (Fats Waller hit)',
	'Certain engine',
	'Sitting place',
	'Command to Fido',
	'In sorry shape',
	'Gawking at',
	'Estuary feature',
	'Hag',
	'Beat',
	'Sphagnous',
	'Sedate',
	'From now on',
	'Small amount',
	'With 10-Across, 1957 Elvis song',
	'Disgrace',
	'Overnight sensation?',
	'Come of age',
	'Like mountains in winter',
	'Upper-story room',
	'Like some concerns',
	'Percolate',
	'Yap, so to speak',
	'Keep after',
	'Stick together',
	'Having a key, in music',
	"TV's George Jefferson, e.g.",
	'Situation for Pauline?',
	'Chessman',
	"Mame's onus",
	'___ cuisine',
	'Used binoculars, maybe',
	'Ruined',
	'Prelim',
	'Underlying',
	'"Rise and ___!"',
	'Lizard with clingy toe pads',
	'Bucking bronco event',
	'Kind of dog',
	'Head of a ranch',
	'Like some good soil',
	'Rascal',
	'Beat it',
	'Virile',
	'"Greetings!"',
	'Speak boastfully of',
	'Club publication',
	'Untamed',
	'Word repeated before "Who\'s there?"',
	"*Newsboy's cry",
	'Individually owned apartment',
	'Go with the flow',
	'"Free" whale of film',
	'Rural dance',
	'Jersey fabric',
	'Go around',
	'Kwanzaa principle',
	'Common sculpture',
	'Part of a book?',
	'"Heavens!"',
	'Not strong',
	'Smooth and glossy',
	'Part of a stairway',
	"'Mid",
	"60's catchword",
	'Squarely',
	'Unkind',
	'Prepare to check E-mail, perhaps',
	'Tape deck button',
	'"I read you"',
	"Burger King, to McDonald's",
	'Free',
	'Install to new specifications',
	'Trunk line',
	'Rated NC-17',
	'One who tries',
	'Oarsman',
	'Cloyingly charming',
	'In the boondocks',
	'Get rid of a shadow',
];

export default clues;
